#!/bin/bash

if [ $# -ne 1 -o "$1" = "-help" -o "$1" = "--help" -o "$1" = "-h" ]; then
  echo "Creates a new cpp project."
  echo "Usage:"
  echo "      new-project <project-name>"
  echo
  exit 0
fi

if [ -e "$1" ]; then
  echo "File already exists: \"$1\""
  exit 1
fi

mkdir "$1"
vim "$1/$1.cpp"
vim "$1/input"
./makeit "$1"
echo "Output:";
cat "$1/output"
exit
